# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app"
client_id = "68eb73f3e71b59ebafe59925cb74e007"
application_url = "https://receptor-discovered-smile-increases.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://receptor-discovered-smile-increases.trycloudflare.com/auth/callback",
  "https://receptor-discovered-smile-increases.trycloudflare.com/auth/shopify/callback",
  "https://receptor-discovered-smile-increases.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mydevstoresub.myshopify.com"
